-- AlterTable
ALTER TABLE "standard_vital_ranges" ALTER COLUMN "maxValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minValue" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minAcceptablePercentage" SET DATA TYPE DOUBLE PRECISION;
