/*
  Warnings:

  - You are about to drop the column `tempC` on the `vent_settings` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "alarms_parameters" ALTER COLUMN "hi_p" DROP NOT NULL,
ALTER COLUMN "hi_p" DROP DEFAULT,
ALTER COLUMN "lo_p" DROP NOT NULL,
ALTER COLUMN "lo_p" DROP DEFAULT,
ALTER COLUMN "low_ve" DROP NOT NULL,
ALTER COLUMN "low_ve" DROP DEFAULT,
ALTER COLUMN "apnea_s" DROP NOT NULL,
ALTER COLUMN "apnea_s" DROP DEFAULT,
ALTER COLUMN "head_of_bed" DROP NOT NULL,
ALTER COLUMN "head_of_bed" DROP DEFAULT,
ALTER COLUMN "pmv" DROP NOT NULL,
ALTER COLUMN "pmv" DROP DEFAULT;

-- AlterTable
ALTER TABLE "flow_sheets" ADD COLUMN     "comments" TEXT,
ADD COLUMN     "signature" TEXT;

-- AlterTable
ALTER TABLE "measured_data" ALTER COLUMN "pip_cmh_2_o" DROP NOT NULL,
ALTER COLUMN "pip_cmh_2_o" DROP DEFAULT,
ALTER COLUMN "peep_cmh_2_o" DROP NOT NULL,
ALTER COLUMN "peep_cmh_2_o" DROP DEFAULT,
ALTER COLUMN "pmean_cmh_2_o" DROP NOT NULL,
ALTER COLUMN "pmean_cmh_2_o" DROP DEFAULT,
ALTER COLUMN "leak_cmh_2_o" DROP NOT NULL,
ALTER COLUMN "leak_cmh_2_o" DROP DEFAULT,
ALTER COLUMN "mve_l_min" DROP NOT NULL,
ALTER COLUMN "mve_l_min" DROP DEFAULT,
ALTER COLUMN "vte_ml" DROP NOT NULL,
ALTER COLUMN "vte_ml" DROP DEFAULT,
ALTER COLUMN "total_rate" DROP NOT NULL,
ALTER COLUMN "total_rate" DROP DEFAULT,
ALTER COLUMN "spont_rate" DROP NOT NULL,
ALTER COLUMN "spont_rate" DROP DEFAULT,
ALTER COLUMN "e_time" DROP NOT NULL,
ALTER COLUMN "e_time" DROP DEFAULT,
ALTER COLUMN "i_time" DROP NOT NULL,
ALTER COLUMN "i_time" DROP DEFAULT;

-- AlterTable
ALTER TABLE "vent_settings" DROP COLUMN "tempC",
ALTER COLUMN "tidalVolumeOrPressure" DROP NOT NULL,
ALTER COLUMN "tidalVolumeOrPressure" DROP DEFAULT,
ALTER COLUMN "iTimeSec" DROP NOT NULL,
ALTER COLUMN "iTimeSec" DROP DEFAULT,
ALTER COLUMN "ieRatio" DROP NOT NULL,
ALTER COLUMN "ieRatio" DROP DEFAULT,
ALTER COLUMN "riseTime" DROP NOT NULL,
ALTER COLUMN "riseTime" DROP DEFAULT,
ALTER COLUMN "iTrigger" DROP NOT NULL,
ALTER COLUMN "iTrigger" DROP DEFAULT,
ALTER COLUMN "fiO2Pct" DROP NOT NULL,
ALTER COLUMN "fiO2Pct" DROP DEFAULT,
ALTER COLUMN "heatedHumidifierTemp" DROP NOT NULL,
ALTER COLUMN "heatedHumidifierTemp" DROP DEFAULT;

-- AlterTable
ALTER TABLE "vital_parameters" ALTER COLUMN "hrBPM" DROP NOT NULL,
ALTER COLUMN "hrBPM" DROP DEFAULT,
ALTER COLUMN "rrBPM" DROP NOT NULL,
ALTER COLUMN "rrBPM" DROP DEFAULT,
ALTER COLUMN "spO2Pct" DROP NOT NULL,
ALTER COLUMN "spO2Pct" DROP DEFAULT;
